### ISSUE TITLE
Moodlebox Prepared disk image - login issues

### ISSUE THREAD

**Issue by jodi319** [martignoni/make-moodlebox#42]
Hi

I have just downloaded and installed Moodlebox version 1.9.5 on my RPi.
I tested in on both RPi 3 and RPi 2.

I launch and I can view http://moodlebox.home from another machine connected to Access Point MoodleBox.

I am unable to login with credentials: u: admin, p: MoodleboxR56.
The same goes for http://moodlebox.home/phpmyadmin; the credentials you supply on your site- u: moodlebox, p: MoodleboxR56 does not work.

Error mesage I get on moodle.home is "Invalid login, please try again" and
phpadmin is " #1045 - Access denied for user 'moodlebox'@'localhost' (using password: YES)"

Can you please help?

**Comment by martignoni** [comment]
You may had misread the documentation on the website: the password is not MoodleboxR56, but **Moodlebox4$** (maybe an encoding problem on your browser?).
